version: 2

sources:
  - name: src
    database: sourcedb
    schema: mk_mall

    tables:
      - name: customers
      - name: orders
      - name: nations
      - name: regions

      - name: suppliers
        config:
          freshness:
            error_after:
              count: 2
              period: day
            warn_after:
              count: 1
              period: day

          loaded_at_field: updated_time